# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 021412286eafaa08239762015321b66beb946a9c7a36d2d3e9b5168c10eda471f8807b6b07320e3cf71ce9d10e24c6c198141c547f924b8cdf6d2bf63a13d766

test:
  secret_key_base: 93fcf20df5bd1b4066d63c1f020c25202ea66490da80d4ffdb5bdd6f78720d8156c22f2a0af6d8738d17b43d84be06e854372488df42350294fe7be5d37310bc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
